### ISSUE TITLE
peerfact menu displays multiple times for certain views

### ISSUE THREAD

**Issue by 0reo** [peerfact/peerfact#12]
This is an ad from Facebook trying to get me to make an ad.  As you can see, the peerfact menu displays in it 3 times

![peerfact-bug](https://cloud.githubusercontent.com/assets/7738818/14622848/dac48544-059a-11e6-9a28-04e213694de0.jpg)

**Comment by Blank101** [comment]
Changing direction. This is no longer necessary.
